spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password: ""
    driver-class-name : org.h2.Driver
  jpa:
    show-sql: true
    generate-ddl: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: update
